# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Development CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  update-manifest-stage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: bright-co/bright-resume-gitops
          ref: main
          token: ${{ secrets.G_TOKEN }}
        run: /
          git config --global user.email "erfan@bright-resume.com"
          git config --global user.name "erfan"
          echo ${{ github.sha }}
          sed -i "s|image: ghcr.io/bright-co/bright-resume-back-auth:\\(.*\\)|image: ghcr.io/bright-co/bright-resume-back-auth:${{ github.sha }}|" ./development/auth.yaml
          git add -A
          git commit -am "update image for - ${{ github.sha }}"
        run: echo ${{ github }}
        run: git push
      
    
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
      
  #     - name: build back-auth 
  #       run: docker build -t ghcr.io/bright-co/bright-resume-back-auth:${{ github.sha }} -f infra/Dockerfile.auth .
      
  #     - name: Docker Login
  #       uses: docker/login-action@v3.0.0
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
      #     password: ${{ secrets.G_TOKEN }}
          
      # - name: push images
      #   run: docker push ghcr.io/bright-co/bright-resume-back-auth:${{ github.sha }}
          
