name: Development CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  update-manifest-stage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: bright-co/bright-resume-gitops
          ref: main
          token: ${{ secrets.G_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.email "erfan@bright-resume.com"
          git config --global user.name "erfan"
      
      - name: Update Image Tag
        run: |
          echo ${{ github.sha }}
          sed -i "s|image: ghcr.io/bright-co/bright-resume-back-auth:.*|image: ghcr.io/bright-co/bright-resume-back-auth:${{ github.sha }}|" ./development/auth.yaml
          git add -A
          git commit -m "update image for - ${{ github.sha }}"

      - name: Push Changes
        run: git push



  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
      
  #     - name: build back-auth 
  #       run: docker build -t ghcr.io/bright-co/bright-resume-back-auth:${{ github.sha }} -f infra/Dockerfile.auth .
      
  #     - name: Docker Login
  #       uses: docker/login-action@v3.0.0
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
      #     password: ${{ secrets.G_TOKEN }}
          
      # - name: push images
      #   run: docker push ghcr.io/bright-co/bright-resume-back-auth:${{ github.sha }}
          
